apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169825580
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169825580
    app.kubernetes.io/part-of: test-app-169825580
  name: java-quarkus-169825580
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169825580
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169825580
    spec:
      containers:
      - image: quay.io/hacdev/hmdcrvro-tenant/test-app-169825580/java-quarkus-169825580@sha256:cf2976b7761234d3ae3203943f8bbdd13fc46510a990dddbee526938d5f805d8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
